### ISSUE TITLE
more output file options please :)

### ISSUE THREAD

**Issue by gprime31** [ozzi-/tld_scanner#2]
This is a great tool, i would like to see more options to save a file like,:
1. plain text not json
2. save with or without ip's
3. just the plain http://xxx and https://xxx in a list for using with amass and other tools.

**Comment by ozzi-** [comment]
Hi @gprime31 
Can you give me an example of the format desired for option 3?
For option 1 I would separate the results by a line break.

Cheers

**Comment by gprime31** [comment]
http://example.com
https://example.com
https://example1.com
http://example1.com
and so on,
single line for each domain. So I can run it through amass and other tools, thanks.

**Comment by gprime31** [comment]
Better explanation:
Plain text file output with:
http://example.com
https://example.com
http://example.ca
https://example.ca
http://example.us
https://example.us
http://example.in
https://example.in
etc.....

**Comment by ozzi-** [comment]
Hi @gprime31 

tld scanner now supports the -m flag:
```
-m <outputmode>   | Sets the output mode, defaults to 'json'
                    json      - json objects, key = url and value = ip
                    jsonarray - json array, entries = urls
                    plain     - plain text, one url per line
```

Hope this helps :)

**Comment by gprime31** [comment]
Awesome!!!! Thanks :)
