### ISSUE TITLE
warnings after fresh install

### ISSUE THREAD

**Issue by gprime31** [ozzi-/tld_scanner#3]
hi,
getting some errors after fresh OS install
did python3 -m pip install -r requirements.txt no difference
maybe a Python 3.8.5 thing?
![2021-05-02_10-27](https://user-images.githubusercontent.com/44535257/116816758-3e2fcf80-ab31-11eb-82bf-ff5bfda74432.png)

**Comment by ozzi-** [comment]
Hi @gprime31  
Really does seem to be due to a change introduced by python 3.8:
https://adamj.eu/tech/2020/01/21/why-does-python-3-8-syntaxwarning-for-is-literal/

**Comment by ozzi-** [comment]
Just tested the behaviour with py 3.9.4 - warnings are gone!
Thanks for bringing this to my attention
